{% set name = "bns-python" %}
{% set version = "9999" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  path: ../

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - colomoto_jupyter >=0.7.0
    - pandas
    - bns

about:
  home: https://github.com/colomoto/bns-python
  summary: 'Python interface to BNS'
  license_family: LGPL
  license: LGPL v3+/CeCILL-C
